version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make test
          name: install deps
      - run:
          command: |
            . venv/bin/activate
            make lint
          name: lint
      - run:
          command: |
            . venv/bin/activate
            make install
          name: test src

workflows:
  main:
    jobs:
      - build-and-test
